"""empty message

Revision ID: 70d09c209dd5
Revises: 76ea43b306f8
Create Date: 2020-07-14 22:17:39.359839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d09c209dd5'
down_revision = '76ea43b306f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('curren_node', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'curren_node')
    # ### end Alembic commands ###
