"""empty message

Revision ID: bc65452d2dc2
Revises: 70d09c209dd5
Create Date: 2020-07-14 23:35:37.525081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc65452d2dc2'
down_revision = '70d09c209dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_node', sa.Integer(), nullable=False))
    op.drop_column('users', 'curren_node')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('curren_node', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'current_node')
    # ### end Alembic commands ###
