"""empty message

Revision ID: d0f63b7e130a
Revises: 1df9f9d4c671
Create Date: 2020-07-21 14:05:14.114975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f63b7e130a'
down_revision = '1df9f9d4c671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipes_image_url_key', 'recipes', type_='unique')
    op.drop_constraint('recipes_recipe_url_key', 'recipes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('recipes_recipe_url_key', 'recipes', ['recipe_url'])
    op.create_unique_constraint('recipes_image_url_key', 'recipes', ['image_url'])
    # ### end Alembic commands ###
